#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SSD_ROOT="${SYNTHETIQ_REDACT_SSD_ROOT:-/Volumes/ZX20/SynthetiqRedact}"
DATA_DIR="$SSD_ROOT/data"
MODEL_DIR="$SSD_ROOT/models"
CACHE_DIR="$SSD_ROOT/cache"
ENV_FILE="$REPO_DIR/.env.mac-ssd"

if [[ ! -d /Volumes/ZX20 ]]; then
  echo "SSD not found at /Volumes/ZX20. Plug in the SSD and try again." >&2
  exit 1
fi

mkdir -p \
  "$DATA_DIR/uploads" \
  "$DATA_DIR/processed" \
  "$MODEL_DIR/ollama" \
  "$CACHE_DIR/huggingface" \
  "$CACHE_DIR/torch" \
  "$CACHE_DIR/easyocr" \
  "$CACHE_DIR/paddle"

cat > "$ENV_FILE" <<EOF
# Synthetiq Redact local Mac SSD runtime config
# Generated by scripts/setup_mac_ssd.sh
SYNTHETIQ_REDACT_DATA_DIR=$DATA_DIR
UPLOAD_DIR=$DATA_DIR/uploads
PROCESSED_DIR=$DATA_DIR/processed
DB_PATH=$DATA_DIR/db.sqlite3
HF_HOME=$CACHE_DIR/huggingface
TRANSFORMERS_CACHE=$CACHE_DIR/huggingface
TORCH_HOME=$CACHE_DIR/torch
EASYOCR_MODULE_PATH=$CACHE_DIR/easyocr
PADDLEOCR_HOME=$CACHE_DIR/paddle
OLLAMA_MODELS=$MODEL_DIR/ollama
ENABLE_MULTI_USER_AUTH=0
APP_ENV=development
EOF

if [[ -d "$REPO_DIR/backend/data" ]]; then
  echo "Copying existing backend/data into SSD data folder without deleting the original..."
  rsync -a --ignore-existing "$REPO_DIR/backend/data/" "$DATA_DIR/"
fi

if [[ ! -d "$REPO_DIR/backend/venv" ]]; then
  echo "Creating backend virtual environment..."
  python3 -m venv "$REPO_DIR/backend/venv"
fi

echo "Installing backend dependencies..."
"$REPO_DIR/backend/venv/bin/python" -m pip install --upgrade pip
"$REPO_DIR/backend/venv/bin/python" -m pip install -r "$REPO_DIR/backend/requirements.txt"
"$REPO_DIR/backend/venv/bin/python" -m spacy download en_core_web_sm

echo "Installing frontend dependencies..."
(cd "$REPO_DIR/frontend" && npm install)

echo ""
echo "SSD setup complete."
echo "Runtime data: $DATA_DIR"
echo "Model/cache data: $SSD_ROOT"
echo "Env file: $ENV_FILE"
echo ""
echo "Start the app with:"
echo "  scripts/run_mac_ssd.sh"
